name = "ricciflowblueprint"
defaultTargets = ["RicciFlowBlueprint"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "RicciFlowBlueprint"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
